name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -PspotlessEnable=false
    - name: App Center CLI
      uses: avocaddo/AppCenter-Github-Action@v1.0.2
      with:
        command: appcenter distribute release --app SmallRaw/ForeTime --file app-foretime/build/outputs/apk/debug/app-foretime-debug.apk --group Testers
        token: ${{secrets.APPCENTER_TOKEN}}
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVER_ACCOUNT_JSON }}
        # The package name, or Application Id, of the app you are uploading
        packageName: com.smallraw.foretime.app 
        # The Android release file to upload (.apk or .aab)
        releaseFile: app-foretime/build/outputs/apk/debug/app-foretime-debug.apk
        # The track in which you want to assign the uploaded app.
        track: alpha # default is production Values: alpha, beta, internal, production, internalsharing
        
