name: Android CI Push Firim

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/local/rubies
        key: ruby-2.6.5
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.66.1
      with:
        ruby-version: 2.6.5
        bundler-cache: true
    - name: install fir.im
      run: gem install fir-cli
    - name: Upload to Fir.im
      run: fir login ${{ secrets.FIRTOKEN }}
    - run: fir publish app-foretime/build/outputs/apk/debug/app-foretime-debug.apk
